### ISSUE TITLE
If PS4 is turned on manually, it can't be turned off via Home Assistant integration

### ISSUE THREAD

**Issue by Vinndimon** [fleXible/ha-ps4-custom#2]
If I turn PS4 on via PS button on the gamepad, it can't be turned off via HA integration. PS4 just does not react to the "Power" button on the HA dashboard. However, it starts working if I reboot the integration from the HA "Integrations" menu.

I use HA supervised. The Core version is 2021.9.7.

**Comment by fleXible** [comment]
@Vinndimon This repo is not part of the official Home Assistant project or any of its integrations but a custom component to be installed as addon using [HACS](https://hacs.xyz/).
Please confirm you have this addon installed and your issue is related to it beeing activated, as I was not able to reproduce your problem.
